<?php
/**
  *
  *
  */
?>
<?php $_session = Mage::getSingleton('admin/session') ?>
<?php

	try {
		$hasValidAcl = $_session->isAllowed(
			$_session->getData('acl')->get("admin/system/config/wordpress")->getResourceId()
		);
	}
	catch (Exception $e) {
		$hasValidAcl = false;
	}

?>
<?php if ($this->getRequest()->getParam('section') !== 'wordpress' || !Mage::helper('wordpress')->isEnabled()): ?>
	<?php return ?>
<?php endif; ?>
<?php $_config = Mage::app()->getConfig() ?>
<?php if ($hasValidAcl): ?>
	<div id="wp-update-msg" class="wp-update-msg" style="display:none;">
		<ul class="messages">
			<li class="notice-msg">
				<ul>
					<li>
						<span>
							<?php echo $this->__('Magento WordPress Integration extension update available.') ?>
							<?php if (Mage::helper('wordpress/system_update')->isGit()): ?>
								<?php echo $this->__('Run \'git pull\' to update to version %s.', '<span id="wp-version"></span>') ?>
							<?php else: ?>
								<a href="<?php echo $this->getUrl('*/wordpress/update') ?>"><?php echo $this->__('Update to version %s automatically.', '<span id="wp-version"></span>') ?></a>
							<?php endif; ?>
						</span>
					</li>
				</ul>
			</li>
		</ul>
	</div>		
<?php endif; ?>		
<div class="content-header" style="margin-bottom: 10px;">
	<table cellspacing="0">
		<tbody>
			<tr>
				<td>
					<h3>
						<?php echo $this->__('Magento WordPress Integration %s', (string)$_config->getNode('modules/Fishpig_Wordpress/version')) ?>
						<?php if (Mage::helper('wordpress')->isWordPressMU()): ?>
							<span style="color:#666;">/</span> 
							<?php echo $this->__('Multisite Integration %s', (string)$_config->getNode('modules/Fishpig_Wordpress_Addon_Multisite/version')) ?>
						<?php endif; ?>
					</h3>
				</td>
				<td class="form-buttons">
					<button style="" onclick="configForm.submit()" class="scalable save" type="button" title="<?php echo $this->__('Save Config') ?>"><span><span><span><?php echo $this->__('Save Config') ?></span></span></span></button>
				</td>
			</tr>
		</tbody>
	</table>
</div>
<div id="fp-integration-test-results">
	<?php if (!$hasValidAcl): ?>
		<div id="messages">
			<ul class="messages">
				<li class="notice-msg">
					<ul>
						<li>
							<span><?php echo $this->__("To finish installing Fishpig's Magento WordPress integration extension, log out of Magento and log back in.") ?></span>
						</li>
					</ul>
				</li>
			</ul>
		</div>
	<?php else: ?>
		<?php if ($errors = Mage::helper('wordpress/system')->getIntegrationTestResults()): ?>
			<div class="grid" style="padding-bottom:10px;">
				<table cellspacing="0" class="data" style="border-left: 0px none;">
						<colgroup>
							<col width="30px" />
							<col />
							<col />
						</colgroup>
						<tbody>
							<?php foreach($errors as $it => $error): ?>
								<tr class="<?php if ($it%2===0): ?>odd<?php else: ?>even<?php endif; ?>">
									<td class="a-center" style="border-color:<?php echo $error->getBgColour() ?>;background-color:<?php echo $error->getBgColour() ?>;">
										<span>&nbsp;</span>
									</td>
									<td style="vertical-align: middle !important;">
										<strong><?php echo $this->__($error->getTitle()) ?></strong>
									</td>
									<td style="vertical-align: middle !important;">
										<span><?php echo $error->getMessage() ?></span>
									</td>
								</tr>
							<?php endforeach; ?>
						</tbody>
					</table>
			</div>
		<?php endif; ?>
	<?php endif; ?>
</div>
<?php echo $this->getChildHtml('extend') ?>
<?php if (Mage::app()->getConfig()->getNode('wordpress/core/modules') === false): ?>
	<script type="text/javascript">document.observe("dom:loaded",function(){$('row_wordpress_misc_include_jquery').remove();$('row_wordpress_misc_include_underscore').remove();});</script>
<?php endif; ?>